### PR TITLE
AppearancePane: More descriptive label for dark style

### PR DESCRIPTION
**Pull request by ryonakano**
elementary OS 6 will support an OS-wide dark preference, but this only works for apps that can detect this preference using `Granite.Settings.prefers_color_schema`; Third-party apps like Google Chrome, Slack, or Visual Studio Code are not switched to dark style according to this preference, and we still need to enable "Prefer dark variant" switch in elementary Tweaks to force these apps to use dark style.

However, I think the current label of this switch might be confusing, so I changed the label string.

### CODE REVIEW

**Comment by Philip-Scott** [comment]
This actually only affects apps that use the dark Gtk Stylesheet, so it may still affect first-party apps like elementary Files. 

image

A better text could be "Force Dark Stylesheet" or something along those lines, what do you think? :)

**Comment by Philip-Scott** [comment]
Ohhh slack *does* also accept it, but only on the file menu and not the actual headerbar :o 

image

I am running Pop_OS + elementary theme though, so let me know if this is not the case as well

**Comment by ryonakano** [comment]
Screenshot from 2020-08-24 10-00-45

Hmm, the headerbar also accepts dark style on my side.

**Comment by Philip-Scott** [comment]
I blame my weird setup then! :P

**Pull request merged**
