### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by roxfr**
Hi,
Could you update the French translation, please.
Thank you.
Cordially,
Roxfr

### CODE REVIEW

**Review by ryonakano — CHANGES_REQUESTED** [review]
Hi! Thank you for your translation!

You seemed to forgot removing the "needs editing" flags on Poedit which are shown as `#, fuzzy` in the .po file; otherwise your translation won't be shown. Would you remove all of these flags?

**Review by ryonakano — APPROVED** [review]
Looks good, thanks!

**Comment by roxfr** [comment]
Ok thank you but I find it strange that Poedit to modify the line breaks in the original values (msgid)
See image below :
Capture

**Comment by ryonakano** [comment]
Ah, it's alright, that should not affect the translation :)

**Pull request merged**
