### PR TITLE
Fix prefer dark style switch state not loading

### LINKED ISSUE #47: Prefer dark style switch not loading state
As the title suggests. To reproduce:
1. Turn on prefer dark mode.
2. Close system settings.
3. Open Tweaks plug.
4. Switch is off but apps are respecting dark style preference.

### PR DESCRIPTION
**Pull request by pongloongyeat**
As title suggests. Fixes #47.

### CODE REVIEW

**Comment by pongloongyeat** [comment]
Would probably make sense to put this under init_data

**Comment by ryonakano** [comment]
Hmm yeah I was silly to remove this during redesign :sweat_smile: https://github.com/pantheon-tweaks/pantheon-tweaks/commit/a667345d159f6395679b3082206771fc24fb7228#diff-398aaf7a390b80e77dc2c4fbb1275c462ca02d7616291086422244686a9205ddL52

**Comment by ryonakano** [comment]
We already sync the state of the switch and the setting in line 114, so you don't need to move this new code to init_data. However, would you move this line under the initialization of dark_style_switch, like this:

```diff
var dark_style_switch = new Switch ();
+ dark_style_switch.state = gtk_settings.prefer_dark_theme;
var prefer_dark_info = new DimLabel (_("Forces dark style on all apps, even if it's not supported. Requires restarting the application."));
```

**Comment by pongloongyeat** [comment]
Marking as ready for review. I've personally tested it and it works fine.

**Review by ryonakano — APPROVED** [review]
Works fine for me too.

**Pull request merged**
